apiVersion: apps/v1
kind: Deployment
metadata:
  name: shorten
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nodeapp
  template:
    metadata:
      labels:
        app: nodeapp
    spec:
      containers:
        - name: shorten-app
          image: first545455/shortname:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
      imagePullSecrets:
        - name: myregistrykey
    