apiVersion: v1
kind: Service
metadata:
  name: myshorten-app-service
spec:
  selector:
    app: nodeapp
  type: LoadBalancer
  ports:
  - port: 5000
    protocol: TCP
    targetPort: 5000
    nodePort: 31110

