apiVersion: apps/v1
kind: Deployment
metadata:
  name: shorten-deployment
  labels:
    app: shorten
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shorten
  template:
    metadata:
      labels:
        app: shorten
    spec:
      containers:
        - name: shorten
          image: /*images ที่ได้จากการ build*/
          ports:
            - containerPort: 5000
          env:
            - name: MONGO_DB_URL
              valueFrom:
                  configMapKeyRef:
                    name: mongodb-configmap
                    key: database_url
            - name: MONGO_DB_PORT
              valueFrom:
                  configMapKeyRef:
                    name: mongodb-configmap
                    key: database_port
---
apiVersion: v1
kind: Service
metadata:
  name: shorten-service
spec:
  selector:
    app: shorten
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000

